@api = http://localhost:5500/products

### Get all Products
GET {{api}}

###     Create new product

POST {{api}}
Content-Type: application/json

{
    "Name": "Prueba",
    "Description" : "Microfono Samsung"
}
###     Create new product

POST {{api}}
Content-Type: application/json

{
    "TipoProducto": "Galletas",
    "Bodega": "J-124",
    "Codigo": "Animalito",
    "FormaVenta": "Directa",
    "Costo": 300.00,
    "Precio": 10.50,
    "Nacionalidad": "Mexico",
    "Calidad": "5",
    "Perecedero": "1"
}
### {
#     "TipoProducto": "1",
#         "Bodega": "2",
#         "Codigo": "Emperador",
#         "FormaVenta": "Directa",
#         "Costo": 450.00,
#         "Precio": 17.00,
#         "Nacionalidad": "Mexico",
#         "Calidad": 5,
#         "Perecedero": 1
# }


### Getting a product
GET {{api}}/5
### Getting a user
GET http://localhost:3000/usuarios

### Delete a product
DELETE {{api}}/5


### Count of Products
GET {{api}}/count

### Update Product

PUT {{api}}/7
Content-Type: application/json

{
    "Name": "Laptop Alienware",
    "Description": "Gaming Laptop HP",
    "Quantity": 50
}

### All Everything

GET {{api}}/todo/count